### ISSUE TITLE
Testing the data quality issues

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/underpass#100]
From https://github.com/hotosm/underpass/issues/97 - @robsavoye  has made a fix to ensure the validation table is up to date with latest OSM snapshot. We have to test this with some sample features

cc @itskshitiz321

**Comment by robsavoye** [comment]
Currently there are test cases for the data quality in Underpass. As work is now shifting towards more focus on data quality, we should add more test cases and test data.
