### ISSUE TITLE
Ensure Users Table is Up to Date and tracking all users 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/underpass#102]
We need to update users table when new user added or when he changes his username and make sure we are tracking all the user within the database and its up to date !

**Comment by itskshitiz321** [comment]
cc : @robsavoye , @ramyaragupathy

**Comment by robsavoye** [comment]
Currently every user is added to the users table in the galaxy database, if the edits from that mapper are within the polygon of the area being processed. (94 countries by default). Underpass also syncs user data with the Tasking Manager as well.

**Comment by emi420** [comment]
I close this issue because we have the users ids and I think maintaining a list of usernames is not an Underpass responsibility anymore. We can create an specific tool for doing that if it's needed for customized reports.
