### ISSUE TITLE
[DEV] Enable Underpass CI Tests in GH Actions

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/underpass#112]
In order to run the tests in CI GH Actions, we will need to make the docker image [underpass_build_deps](https://quay.io/repository/hotosm/underpass-build-deps) work properly. Right now it is failing: https://github.com/hotosm/underpass/runs/5184846666?check_suite_focus=true

**Comment by robsavoye** [comment]
This is now fixed.
