### ISSUE TITLE
Document data validation in Underpass

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/underpass#149]
Output will be a document with technical details on how do we capture:
* overlapping buildings
* bad geometry buildings

**Comment by ramyaragupathy** [comment]
Will be a markdown file within GitHub

cc @petya-kangalova

**Comment by itskshitiz321** [comment]
Code cleanup is Going on !

**Comment by ramyaragupathy** [comment]
Information updated in the documentation https://hotosm.github.io/underpass/md_doc_validation.html
