### ISSUE TITLE
Validating bad geometry and bad tag combination data outputs

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/underpass#153]
Right now we have a dump shared via https://www.senecass.com/HOT/ for anyone who wants to review the bad geometry data outputs. We should generate more outputs and share the definitions for the community to validate the  Underpas validation

cc @LeenDhondt @robsavoye @itskshitiz321 @emi420

**Comment by emi420** [comment]
This is done. We are continually sharing and discussing data quality outputs for both bad geometry and bad tag combinations.
