### ISSUE TITLE
Running underpass on EC2 24/7

### ISSUE THREAD

**Issue by itskshitiz321** [hotosm/underpass#154]
This ticket is to get Underpass process running on development setup and monitoring on a regular basis.

cc @robsavoye @emi420

**Comment by itskshitiz321** [comment]
Replicator is running now on EC2 Dated Yesterday , started repopulating data in RDS ! Currently started from previous year cc : @emi420

**Comment by emi420** [comment]
Should I close this issue then? @itskshitiz321

**Comment by ramyaragupathy** [comment]
Yes - if this is running on EC2 we are good to close here @emi420 

cc @itskshitiz321 @robsavoye

**Comment by robsavoye** [comment]
I just made a change to the database schema, adding a new column, so after recompiling underpass with his change, you'll need to add this column to the RDS database before replicator will run. Then restart it from July 2020. The new 'values' column should do a proper upsert, but check that any status field with 'badvalue' is now getting the actual bad values added.
