### ISSUE TITLE
Underpass doesn't store all changesets that are meant to save to table from file after area filter

### ISSUE THREAD

**Issue by itskshitiz321** [hotosm/underpass#164]
This is more technical issue which is related to previous issue that it is missing changesets , To debug this I have disabled all the areaFilter , Option and let underpass process all the changesets from file without comparing them to priority countries , I have debugged the query generated by underpass to verify either we have issue with query or not but seems like it is problem in parsing when we parse xml with <changeset> 
Example of debug : 
This osm file is downloaded from directory that is downloaded by underpass itself 
![image](https://user-images.githubusercontent.com/36752999/161926155-751a1611-7036-4c92-97d9-cb761fa8d5ee.png)
This file has changeset info from 118346246-257
When checked on query , we have only few
![image](https://user-images.githubusercontent.com/36752999/161926491-09170266-6cc9-4894-8449-693630465b58.png)
Verified from table itself 
![image](https://user-images.githubusercontent.com/36752999/161926930-9b647b38-f613-4e36-89e3-1203bc7e362a.png)

I think creating a test case for changeset processing and a changefile will be the first thing to do

**Comment by itskshitiz321** [comment]
- Relates to #79 , #84

**Comment by robsavoye** [comment]
I just pushed a fix for this (#6cc7024). Instead of using the centroid to identify if the changeset is in the priority boundary, instead the bounding box of the changeset is checked to see if it overlaps with the priority boundary. Some of the changesets were so huge that the centroid was winding up in a different continent,
