### ISSUE TITLE
Compare statistics between underpass and insights

### ISSUE THREAD

**Issue by robsavoye** [hotosm/underpass#174]
To find bugs in underpass's statistics calculations, this is a python script that compare the results for every row in the Galaxy database changesets table, and use the Galaxy-API to compare the results and look for errors in underpass.

**Comment by emi420** [comment]
![Screen Shot 2022-04-20 at 11.38.53.png](https://images.zenhubusercontent.com/6230ac8e94a5cb2f9cc49ce2/a74fcc1f-fc10-494b-8bac-fb2b65e4f60d)
