### ISSUE TITLE
Migrate existing data from dev setup to production RDS

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/underpass#176]
Per chat w/ @eternaltyro - while creating a production setup for RDS, it will be handy to use [Data Migration Services](https://aws.amazon.com/dms/) to move existing data from dev RDS to production RDS.

cc @dakotabenjamin @robsavoye

**Comment by emi420** [comment]
I close this issue as we're currently using the server as a production one and local machines for development. If we create other instances for `development` and/or `staging` we can create new issues for addressing the needs regarding migration or deployment.
