### ISSUE TITLE
Documentation main/landing page is empty

### ISSUE THREAD

**Issue by elpaso** [hotosm/underpass#26]
I'm not sure how it is supposed to look, but this is how I see it:

![immagine](https://user-images.githubusercontent.com/142164/127971541-3b94a83f-49c6-46a4-add2-4978a3500ef8.png)

https://robsavoye.github.io/html/index.html

**Comment by robsavoye** [comment]
The link got changed when the repository became public. it's now at:
https://hotosm.github.io/underpass/index.html

**Comment by elpaso** [comment]
Fixed by https://github.com/hotosm/underpass/pull/27
