### ISSUE TITLE
Missing Changesets and Metadata info in Development RDS 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/underpass#306]
After the recent fix , I have found some missing changesets and also some changesets with missing metadata on the RDS , I have tested data for 2022 
For the data 2022-01-19  to 2022-01-22  (UTC Time zone ) under hashtag of missingmaps 
This is the difference I have noticed on RDS : 
```
  Total number of changeset that should be in DB within priority area : 3302,
  Total changeset found on RDS by hashtag : 416,
  Total Changeset missing on stats : 2886,
  Total changeset found on RDS by changeset id : 1364,
  Total changeset which are present on RDS but missing metadata : 948,
  Total changeset which are not present in RDS at all : 1938,
```
Difference is huge ! Here are the missing changeset from RDS 
Here is one example that is supposed to be in RDS 
https://www.openstreetmap.org/changeset/116425922
and Here is one example which doesn't have meta data of hashtag : 
https://www.openstreetmap.org/changeset/116378453 
![image](https://user-images.githubusercontent.com/36752999/184112501-553ddaeb-a0a9-4d11-b66f-6022b3fbf6de.png)

I have attached full excel sheet of changeset id of missing changesets and changesets with missing metadata here 
https://docs.google.com/spreadsheets/d/1KQiidcagcjOHtjmbMSFnLWBBxqbN3XnikWmipPdu3Uw/edit?usp=sharing

cc: @emi420 @ramyaragupathy

**Comment by emi420** [comment]
@kshitijrajsharma Changeset 116425922 is in Tajikistan, outside the priority boundary:

https://github.com/hotosm/underpass/blob/master/data/priority.geojson

**Comment by emi420** [comment]
@kshitijrajsharma For the hashtag issue, yes, there's a bug when collecting hashtags from comments. 

It's working in this case:

```xml
<tag k="comment" v="#hotosm-project-4892;#missingmaps;#salesforce;#salesforceleads;#salesforcelsUK"/>
```

But not in this one:

```xml
<tag k="comment" v="#hotosm-project-4892 #missingmaps #salesforce #salesforceleads #salesforcelsUK"/>
```

I've created a test for hashtags and I'm working on fixing this issue.

**Comment by emi420** [comment]
The issue with hashtags was fixed. Now the testing endpoint for comparing results against Insights is not returning missing data:

```json
{
  "changeset_detected_in_priority_by_insight": 1199,
  "total_changeset_found_by_hashtag": 1200,
  "total_changeset_missing_on_stats": -1,
  "total_changeset_found_by_id": 1199,
  "total_changeset_missing_metadata": -1,
  "changeset_missing_from_db": 0,
  "download_changeset_missing_from_db": "http://52.203.15.233:8000/v1/test_changeset/download_changeset_missing_from_db/2018-08-09/2018-08-10/missingmaps",
  "download_changeset_missing_metadata": "http://52.203.15.233:8000/v1/test_changeset/download_changeset_missing_metadata/2018-08-09/2018-08-10/missingmaps"
}
```
