### ISSUE TITLE
Feature Request : Add last updated date on Database Table 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/underpass#318]
Currently there is no clear way  for api to grab the last timestamp of planet osm dataset available on underpass . API can look into changeset table and filter latest dataset and timestamp of that changeset but it is not accurate because underpass may keep processing planet file during that time and not finished the planet file , it would be great if there will be small table called replication status which will be updated after underpass completes planet replication process , so that we can know until when data is available !

**Comment by robsavoye** [comment]
I'm not sure this is necessary. If replicator is always running, it'll never complete. If the data isn't available, the end user just has to wait a minute or so.

**Comment by emi420** [comment]
I close this issue as is not necessary. Latest data will be always the latest processed replication file, something that is in the database already.
