### ISSUE TITLE
Enhancement: assess performance gains using DuckDB over Postgres

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/underpass#422]
I'm not sure if this is possible, as lots of HOT projects rely on Postgres already.

Postgres (+Postgis) is an awesome general database.

DuckDB is designed specifically for analytical workloads and optimized for fast query execution.
It uses a columnar storage format and vectorized execution model to achieve high performance.

Spatial support was recently added: https://duckdb.org/docs/extensions/spatial.html
So DuckDB now has a lot of the same ST_ functions as Postgis.

It would be neat to benchmark the two and see if Underpass could benefit from using DuckDB underneath.

**Comment by emi420** [comment]
Hey @spwoodcock ! Thanks for your suggestion, but we're not currently thinking into change the database engine. As you said, lots of HOT projects rely on Postgres already, but also other projects that we're depending for now (ex: osm2psql). 

That being said, we can re-open this issue in the future and discuss about it. As a technical note, almost all DB queries are being built in a few files responsible for 3 different main things (statistics, raw data and validation), so is not really that hard to change the database engine.
