### ISSUE TITLE
Compatibility between Underpass and Raw Data API

### ISSUE THREAD

**Issue by emi420** [hotosm/underpass#425]
The database structure must be the same, so data will be compatible between both projects.

1. Use the same LUA script for importing raw data and update the database structure
2. Update Python API 

After these changes, Underpass will work the same way than today, but its database will be compatible with [Raw Data API ](https://github.com/hotosm/raw-data-api).

**Comment by robsavoye** [comment]
As part of our push to modularization where possible, I have a new python module for working with the raw database. It's in it's early stages right now. It's focused on data extraction, not updating the data. I'd like to see anything that accesses the schema we are using in this module where possible. I have looked at the raw-data-api code, Export Tool, FMTM all of which need to access data from postgres, so it seems a good choice for a standalone module that can be shared between all of our projects. https://github.com/hotosm/osm-rawdata
