### ISSUE TITLE
change-set id in the changesets table doesn't make sense

### ISSUE THREAD

**Issue by omranlm** [hotosm/underpass#43]
Running underpass to calculate stats starting Jul 2020 with hour sequence # 000/068/369

When checking the loaded changesets statistics, found some changetset IDs which doesn't make since as they don't exists in osm yet such as # 836844032 which has "highway"=>"2", "highway_km"=>"11597458" in its added hstore values.
Please advise.
![image](https://user-images.githubusercontent.com/39491329/129057009-d4cd09d5-1e9e-450e-bfcd-3084c763a2e4.png)

**Comment by omranlm** [comment]
@robsavoye after the new deb installation, looks like the change set ID is correctly inserted now.

A follow up on this issue with some data that helps to troubleshoot is below,

changeset id = 87369123 , the modified field is empty although this change set has [2 modified highways](https://www.openstreetmap.org/api/0.6/changeset/87369123/download)
![image](https://user-images.githubusercontent.com/39491329/132228149-c3ab5acf-bd4f-4143-8dd5-831745eacd2a.png)

**Comment by robsavoye** [comment]
I need to keep digging into this deeper, but the two modified highways aren't in the priority area, so get ignored.

**Comment by omranlm** [comment]
The 2 modified highways have those 2 way ID 815923836 and 815951903 and both are in the same changeset # 87369123 , so even both **added and modified** highways in this changeset are in the priority are or both aren't.

The whole changeset is in Uganda which is a priority area I believe.

![image](https://user-images.githubusercontent.com/39491329/132513432-183b6042-5106-41d1-8b7b-268274c5bd01.png)

**Comment by robsavoye** [comment]
This appears to have been an artifact left over from multiple runs during debugging. The version on the EC2 instance local postgres is wrong, but the newer non-debugging version it does have the statistics fields.
