### ISSUE TITLE
Optimise dockerfiles (multi-stage, caching)

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/underpass#439]
- The dockerfiles could be optimised to be multi-stage & grouping commands into layers.
- We should also create layers that can be cached easily first, then add layers that break cache later in the file.
- While doing this, there is no harm adding more descriptive labels to images too.

I'm happy to contribute this if you assign me 😄 

Also, I am getting errors trying to build the underpass image (I can also look into this when optimising, if needed):

```
8.207 checking for ld... /usr/bin/ld -m elf_x86_64
8.207 checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
8.208 checking for shared library run path origin... done
8.222 checking 32-bit host C ABI... no
8.231 checking how to run the C preprocessor... gcc -E
8.260 checking for ELF binary format... yes
8.265 checking for the common suffixes of directories in the library search path... lib,lib,lib64
8.277 checking for CFPreferencesCopyAppValue... no
8.288 checking for CFLocaleCopyPreferredLanguages... no
8.299 checking for GNU gettext in libc... yes
8.338 checking whether to use NLS... yes
8.338 checking where the gettext function comes from... libc
8.353 checking that generated files are newer than configure... done
8.353 configure: creating ./config.status
8.691 config.status: error: cannot find input file: `Makefile.in'
------
failed to solve: process "/bin/sh -c ../configure &&     make -j $(nproc) &&     make install" did not complete successfully: exit code: 1
```

**Comment by spwoodcock** [comment]
Working for me now too!
Must have been an issue with the build at the time 😄

**Comment by emi420** [comment]
The `underpass` command is not working on the Docker container, displaying a warning and also failing when looking for a configuration file:

```
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
Couldn't open /usr/local/lib/underpass/config/replicator/planetreplicator.yaml
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
appuser@224e86da4e1e:/code/build$ ls /usr/local/lib/underpass/config/replicator/
ls: cannot access '/usr/local/lib/underpass/config/replicator/': No such file or directory
```

Also, there's an issue with testing that needs to be fixed. 

I re-open this issue for now, until all these things are solved.

**Comment by spwoodcock** [comment]
Thanks @emi420 - will look into adding the config files in the correct places.

The warning

```
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
```

suggests you are using docker via an emulated system, most likely on MacOS.
Is this the case?

**Comment by emi420** [comment]
Yes @spwoodcock , the message was not present previously, maybe because we were using Ubuntu. Isn't something important though.

**Comment by emi420** [comment]
The config files are copied by `make install`
