### ISSUE TITLE
Build and test should not pass when there's a test that is failing and returning 1

### ISSUE THREAD

**Issue by emi420** [hotosm/underpass#451]
I made a test fail and return 1 intentionally:

https://github.com/hotosm/underpass/commit/42bf839c61f3c6d9b70b117df918059c723514ee

But the [Build and Test](https://github.com/hotosm/underpass/actions/workflows/tests.yml) workflow is passing:

<img width="180" alt="Screenshot 2023-12-07 at 20 02 45" src="https://github.com/hotosm/underpass/assets/1226194/af20b483-ccf6-4a7d-a469-19aa696f966f">

With the previous workflow, if a test failed and returned 1, the result was an error and a red badge. 

Here's what I was using before:

```
# Build and run tests
      - name: Build and run tests 
        run: |
          docker-compose -f docker-compose.yml exec -T underpass sh -c "cd /code/build && make check -j `nproc`"
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "Test failed with exit code $exit_code"
            exit $exit_code
          fi
```

**Comment by spwoodcock** [comment]
Thanks for checking - I have a feeling the testing tool is not being invoked as PID 1 in the container, so the signals are not correctly passed on the output. 

GitHub workflows require a signal to determine if they pass or fail.

In order of preference:

Option 1: adding `init: true` to the compose service may fix this.

Option 2: use a tool like `dumb-init` to correctly pass signals. 

Option 3: wrap the docker compose command in $() as you did previously, to manually extract the returned signal.

I can check this when I get time if needed.
