### ISSUE TITLE
[OUT-199] Backup database daily

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/underpass#47]
[OUT-199]([OUT-199]Backup database daily)

[OUT-199]: https://hotosm.atlassian.net/browse/OUT-199

**Comment by dakotabenjamin** [comment]
Test comment

**Comment by dakotabenjamin** [comment]
OUT-198

**Comment by emi420** [comment]
I close this issue because it's very old, if we need backups we can create a new issue later.
