### ISSUE TITLE
Cache state.txt information for diffs from planet

### ISSUE THREAD

**Issue by elpaso** [hotosm/underpass#50]
# Goal

The goal is to identify the right OSC file to download given a timestamp and a planet url.

# Use case

In order to keep the local `osm2pgsql` DB in sync and to compute statistics Underpass needs to be able to
identify the correct diff(s) for a given timestamp or time range.

The planet structure is described by https://wiki.openstreetmap.org/wiki/Planet.osm/diffs and allows to retrieve the diff file `.osc.gz` for a known sequence number, sequence numbers have an associated timestamp which is only exposed in the `state.txt` file which corresponds to the given sequence.

Underpass API needs a method to retrieve this information from a planet server and cache them for future use.

# Implementation plan

Underpass already have methods and classes to handle state information after they have been stored into the cache but it currently misses a way to populate the cache itself which is the main objective of this enhancement.

The proposed implementation will build on top of the current `underpass::Planet` class by implementing a series of methods to retrieve state information for a given timestamp on-demand, the information will be first searched in the cache and transparently retrieved from the planet server and added to the cache after a cache miss.

# Client code example

```c++

Planet planet("https://planet.maps.mail.ru");
const auto osc {planet.findData(replication::minutely, time_from_string("2016-08-04 09:03"))};

```

**Comment by robsavoye** [comment]
This is related to issue: https://github.com/hotosm/underpass/issues/52

**Comment by robsavoye** [comment]
Underpass no longer uses state.txt files.
