### ISSUE TITLE
Re-enable state.txt file processing

### ISSUE THREAD

**Issue by robsavoye** [hotosm/underpass#52]
State.txt files are used when launching Underpass to find the starting path on the remote planet server with all the replication files. This was disabled when doing some refactoring, and should be reenabled with any changes needed.

**Comment by elpaso** [comment]
Maybe fixed by https://github.com/elpaso/underpass/commit/9b5f03554d1fd3e5d31567ff1d50c4828b1da1ae

This apparently works for me: `replicator -p planet.maps.mail.ru -u 004/702/001 -m -v -d`

**Comment by robsavoye** [comment]
Underpass no longer uses state.txt files at runtime.
