### ISSUE TITLE
Stats Enhancement  

### ISSUE THREAD

**Issue by itskshitiz321** [hotosm/underpass#76]
Stats generated from underpass is not matching with insights , need to find breach ! 
The buildings are first priority

**Comment by itskshitiz321** [comment]
Here, Building are being pushed to db 

https://github.com/itskshitiz321/underpass/blob/8689f9a8dd61afc8c767bf5a928ddfa81a31dad8/galaxy/osmchange.cc#L673-L687

**Comment by itskshitiz321** [comment]
Here Buildings and amenities are being pushed ,
https://github.com/hotosm/underpass/blob/8689f9a8dd61afc8c767bf5a928ddfa81a31dad8/galaxy/osmchange.cc#L673-L687

**Comment by ramyaragupathy** [comment]
We need to bring consistency in feature definition for feature parity comparison.

**Comment by robsavoye** [comment]
There will always be some discrepancies between using historical data, and processing minutely replication files. The smaller files don't always contain all the data you need for calculations. If you use hourly or daily updates, you get a closer match, but never with minutely diffs. The upside is gaining real-time abilities, and much faster query performance.
