### ISSUE TITLE
Get organization data from TM

### ISSUE THREAD

**Issue by robsavoye** [hotosm/underpass#77]
Currently Underpass gets some of the user fields from the TM. To support training data integration, the organization data should also be used to populate the organization table in Galaxy so they match. The TM organization data is a subset of the Galaxy table, but this will keep the organization IDs and name in sync.

This is needed to integrate training data into reports, since they reference the organization,

**Comment by emi420** [comment]
I close this issue because integration with TaskingManager is not being done by querying the TM database. The plan is to have Underpass as a standalone product that can be integrated to any other product, without being dependent of TM.
