### ISSUE TITLE
Flag : Overlapping POI and Polygon for Building Count

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/underpass#78]
Flag:  Here changeset 96783104 feature is a node, not a polygon but tagged as an amenity: school and hence counted as a building which is not a bug but the problem is the building that is just beneath the POI is also counted as a building which means currently underpass is counting same building twice (One from Polygon and another from POI when both features intersect) which is providing false statistics . We should remove replication and the building count should be 1 even the feature are replicating. 
An example can be seen here :
https://www.openstreetmap.org/changeset/96783104#map=16/12.6326/-8.0501

**Comment by ramyaragupathy** [comment]
We have to arrive at definitions for different features

**Comment by emi420** [comment]
I remove this issue because this feature is not longer necessary.
