### ISSUE TITLE
Enhancement : Validation for null changesets

### ISSUE THREAD

**Issue by itskshitiz321** [hotosm/underpass#83]
Currently, we are ignoring changeset like this 
https://www.openstreetmap.org/changeset/96764200
![image](https://user-images.githubusercontent.com/36752999/144380816-bdcf4edc-c83f-4ce8-968f-3126dd456615.png)

These changeset does not have geometry and they don't have any changes , they are null. Currently, we are completely ignoring those changesets in the underpass but instead of ignoring what we can do is we can keep them in the database and raise an issue inside the validation table . There are plenty of changesets like this , can be found in insight. Since insight is storing them

**Comment by itskshitiz321** [comment]
cc : @robsavoye

**Comment by mmd-osm** [comment]
OSM API dev here. There's actually nothing wrong with such changesets - nless you're creating tons of them, in which case your editor app might get blocked eventually. I wonder what kind of "insight" you can derive from such a changeset.

**Comment by robsavoye** [comment]
Luckily underpass isn't producing these changesets, just processing them. They are probably safe to ignore as they contribute nothing to statistics collection or data validation.
