### ISSUE TITLE
Flag: Geometry of changeset is stored as null even they have one 

### ISSUE THREAD

**Issue by itskshitiz321** [hotosm/underpass#84]
Let’s take this changeset as an example ,
https://www.openstreetmap.org/changeset/110814309
Can you see geometry in this changeset ? Yes I can 
But in underpass it is null
![image](https://user-images.githubusercontent.com/36752999/144384572-89f4c10e-8b0d-453a-879e-1b7889187afc.png)
But if you have a look at this inside insight it has geometry : 
![image](https://user-images.githubusercontent.com/36752999/144384622-4ebb3997-b6c6-44e0-87ff-41a3dab5febd.png)
How this will affect our stat ? 
This will not affect the stat calculation that underpass is doing but the question is how we are finding whether it is inside our priority area or not ? And also when we are escaping geometry and when we will  be  providing custom polygon stat from API end it will also provide incomplete stat because this changeset doesn't have geometry in the underpass and will not be included in any polygon , These changesets will be missed in stats
More Examples : 
https://www.openstreetmap.org/changeset/110814313
https://www.openstreetmap.org/changeset/88698947
https://www.openstreetmap.org/changeset/88698950
https://www.openstreetmap.org/changeset/88698964
https://www.openstreetmap.org/changeset/88698972
And a lot more … Here is a snip from the underpass changeset table 
![image](https://user-images.githubusercontent.com/36752999/144384832-66f0a261-b142-471f-bfc3-f2276274525b.png)
And From insight table for same changeset id 
![image](https://user-images.githubusercontent.com/36752999/144384869-1b634349-fa3a-4169-acbd-d58cdb2d7d1f.png)

**Comment by itskshitiz321** [comment]
cc : @robsavoye

**Comment by itskshitiz321** [comment]
Confirming Issue still lies , Example changesets : 100939923 , 100939915 Processed by underpass on 2022-03-24 18:42:38.391 +0545  
![image](https://user-images.githubusercontent.com/36752999/159922579-8d88324e-c1bd-4438-a0ab-f462176b5340.png)
![image](https://user-images.githubusercontent.com/36752999/159922652-917d3f76-b734-4e09-b7b8-9d3bf843fc05.png)

**Comment by itskshitiz321** [comment]
**Update on the issue :** 
Figured out there is a same kind of error : 
When there is bbox is null then those fields are also null 
![image](https://user-images.githubusercontent.com/36752999/160875548-bbae5809-2c2e-4937-971a-73ef290ec20d.png)

**Comment by robsavoye** [comment]
I believe this is a bug in storing the geometry for a way. Right now for ways the coordinates are stored as a linestring. At one point I started also storing them as a polygon. I noticed that when the geometry is NULL, the POLYGON field in the OsmWay is NULL, but the linestring filed is fully populated and correct. Since a polygon is just a linestring where the first and last point are the same, we should probably just use linestring, as that'll also apply to highways. This was obviously a work in progress, so the bug is simply that wasn't completed.

**Comment by itskshitiz321** [comment]
During debugging , Changefiles will not have those attribute and missing changeset will cause this value to be left even when processing is finished because changefile and changesetfile will not synchronise and hence missing changeset will cause null value on those row which are processed from changefile and not skipped in changeset processing , caused by : #79

**Comment by itskshitiz321** [comment]
When changeset is filtered and removed during areafilter in underpaass we need to check either that changeset row exists or not in table if it does we need to remove that row ( because that row may have processed from changefile already because in changefile we don't know where it is coming from hence it doesn't include any filteration )
