### ISSUE TITLE
Enhancement : Implement indexes in Geoboundaries Table 

### ISSUE THREAD

**Issue by kshitijrajsharma** [hotosm/underpass#88]
Currently, we don't have indexes in geoboundaries table. We can use btree in id and gist in the boundary column for faster queries.

**Comment by robsavoye** [comment]
Done as of #21d5013.

**Comment by robsavoye** [comment]
Since there are multiple boundaries with the same ID, this table needs a different unique ID.

**Comment by robsavoye** [comment]
I think what needs to happen is rework the geoboundaries table. SInce many countries have associated islands, I originally had created multiple rows for each country sharing an ID. I each country needs to have a single row, and use a multipolygon instead. Then there can be a unique index.

**Comment by ramyaragupathy** [comment]
@itskshitiz321 @robsavoye - it will be useful to document the process of creating these multipolygon boundaries for all the countries. @omranlm - can you please post how do you handle country multipolygons within [Insights](https://github.com/hotosm/insights)?

**Comment by itskshitiz321** [comment]
@ramyaragupathy  I am documenting it !

**Comment by ramyaragupathy** [comment]
Initial findings from @itskshitiz321 on the boundary issues from our two data sources - our next step would be to identify a reliable data source for the country polygons. we are prioritising for the first quarter of 2022

cc @robsavoye @omranlm @JorgeMartinezG

**Comment by emi420** [comment]
I close this issue because it's very old and not relevant anymore.
