### ISSUE TITLE
Underpass is not calculating newly created changeset's statistics 

### ISSUE THREAD

**Issue by itskshitiz321** [hotosm/underpass#92]
![image](https://user-images.githubusercontent.com/36752999/145174975-8c052287-7a59-45b2-9fd8-e25c7106ccdc.png)
Sample Changesets to go through : 
https://www.openstreetmap.org/changeset/114684067
https://www.openstreetmap.org/changeset/114684846
https://www.openstreetmap.org/changeset/114684822

**Comment by ramyaragupathy** [comment]
Might be related to #99
