### ISSUE TITLE
Ensure validation data is up to date with latest from OSM

### ISSUE THREAD

**Issue by ramyaragupathy** [hotosm/underpass#97]
While capturing features for validation/data quality issues like bad geometry/incorrect tag values - we also have to ensure the validation table is up to date once someone fixes it on OSM.

@robsavoye is working on a code fix to implement this change

**Comment by robsavoye** [comment]
Fixed as of #28077bb.

**Comment by ramyaragupathy** [comment]
Keeping this open till we have it deployed on RDS - related comment https://github.com/hotosm/galaxy-ui/pull/13#issuecomment-1020941720

cc @itskshitiz321 @omranlm @d-rita
