### ISSUE TITLE
Refactor threading to improve performance

### ISSUE THREAD

**Issue by robsavoye** [hotosm/underpass#98]
There are some current issues with the current thread code in Underpass that has database connections happening frequently in many spawned threads which reduces the performance. This task is to refactor away from the external thread_pool header file, and use boost::asio::pool instead. Also there should be only one monitor thread per data source, those shouldn't be in the thread_pool. The threadMonitor* functions should implement the thread_pool instead. All threads should share the database connection, instead of connecting all the time.

**Comment by emi420** [comment]
Underpass is using `boost::asio::pool`, there's only one monitor thread per data source and threads are sharing the database connection. We can close this issue.
